// src/components/CalendarWidget.svelte
<script>
  let currentDate = $state(new Date())
  let mounted = $state(false)
  
  const DAYS = ['日', '一', '二', '三', '四', '五', '六']
  
  function getDaysInMonth(year, month) {
    return new Date(year, month + 1, 0).getDate()
  }
  
  function getFirstDayOfMonth(year, month) {
    return new Date(year, month, 1).getDay()
  }
  
  function generateCalendar() {
    const year = currentDate.getFullYear()
    const month = currentDate.getMonth()
    const daysInMonth = getDaysInMonth(year, month)
    const firstDay = getFirstDayOfMonth(year, month)
    
    const calendar = []
    for (let i = 0; i < firstDay; i++) {
      calendar.push(null)
    }
    for (let i = 1; i <= daysInMonth; i++) {
      calendar.push(i)
    }
    return calendar
  }
  
  function prevMonth() {
    currentDate = new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1)
  }
  
  function nextMonth() {
    currentDate = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1)
  }
  
  function goToToday() {
    currentDate = new Date()
  }
  
  const today = new Date()
  const calendarDays = $derived(generateCalendar())
  const currentMonth = $derived(currentDate.getMonth() + 1)
  const currentYear = $derived(currentDate.getFullYear())
  
  import { onMount } from 'svelte'
  onMount(() => {
    requestAnimationFrame(() => { mounted = true })
  })
</script>

<div class="calendar-widget" class:mounted>
  <div class="calendar-header">
    <button class="nav-btn" onclick={prevMonth} aria-label="上一月">
      <i class="fa-solid fa-chevron-left"></i>
    </button>
    <button class="calendar-title" onclick={goToToday} aria-label="回到今天">
      {currentYear}年{currentMonth}月
    </button>
    <button class="nav-btn" onclick={nextMonth} aria-label="下一月">
      <i class="fa-solid fa-chevron-right"></i>
    </button>
  </div>
  
  <div class="calendar-weekdays">
    {#each DAYS as day}
      <span class="weekday">{day}</span>
    {/each}
  </div>
  
  <div class="calendar-days">
    {#each calendarDays as day}
      <span 
        class="calendar-day" 
        class:other-month={!day}
        class:today={day === today.getDate() && 
                   currentMonth === today.getMonth() + 1 && 
                   currentYear === today.getFullYear()}
      >
        {day || ''}
      </span>
    {/each}
  </div>
</div>

<style>
  .calendar-widget {
    width: 260px;
    padding: 18px;
    background-color: rgba(26, 26, 26, 0.45);
    border: 1px solid #2a2a2a;
    border-radius: 16px;
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
    opacity: 0;
    transform: translateX(16px);
    transition: opacity 0.6s ease, transform 0.6s ease;
  }
  
  .calendar-widget.mounted {
    opacity: 1;
    transform: translateX(0);
  }
  
  .calendar-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 16px;
  }
  
  .nav-btn {
    background: none;
    border: none;
    color: #888;
    cursor: pointer;
    font-size: 12px;
    padding: 4px;
    transition: color 0.2s;
    width: 28px;
    height: 28px;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 6px;
  }
  
  .nav-btn:hover {
    color: #fff;
    background: rgba(255, 255, 255, 0.08);
  }
  
  .calendar-title {
    background: none;
    border: none;
    font-size: 13px;
    font-weight: 600;
    color: #fff;
    cursor: pointer;
    padding: 4px 8px;
    border-radius: 6px;
    transition: background 0.2s;
  }
  
  .calendar-title:hover {
    background: rgba(255, 255, 255, 0.08);
  }
  
  .calendar-weekdays {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 4px;
    margin-bottom: 8px;
  }
  
  .weekday {
    font-size: 10px;
    color: #666;
    text-align: center;
    padding: 6px 0;
  }
  
  .calendar-days {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 4px;
  }
  
  .calendar-day {
    font-size: 11px;
    color: #ccc;
    text-align: center;
    padding: 8px 0;
    border-radius: 8px;
    cursor: default;
    transition: background 0.2s;
  }
  
  .calendar-day:hover:not(.other-month) {
    background: rgba(255, 255, 255, 0.08);
  }
  
  .calendar-day.other-month {
    color: #333;
  }
  
  .calendar-day.today {
    background: rgba(255, 255, 255, 0.15);
    color: #fff;
    font-weight: 600;
  }
  
  @media (max-width: 1200px) {
    .calendar-widget {
      display: none;
    }
  }
</style>

// components/CalendarWidget.tsx
'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'

export default function CalendarWidget() {
  const [currentDate, setCurrentDate] = useState(new Date())

  const year = currentDate.getFullYear()
  const month = currentDate.getMonth()

  const firstDay = new Date(year, month, 1).getDay()
  const daysInMonth = new Date(year, month + 1, 0).getDate()

  const today = new Date()
  const isCurrentMonth = today.getFullYear() === year && today.getMonth() === month

  const prevMonth = () => {
    setCurrentDate(new Date(year, month - 1, 1))
  }

  const nextMonth = () => {
    setCurrentDate(new Date(year, month + 1, 1))
  }

  const weekDays = ['日', '一', '二', '三', '四', '五', '六']

  const renderDays = () => {
    const days = []
    for (let i = 0; i < firstDay; i++) {
      days.push(<div key={`empty-${i}`} className="h-7" />)
    }
    for (let i = 1; i <= daysInMonth; i++) {
      const isToday = isCurrentMonth && today.getDate() === i
      days.push(
        <motion.div
          key={i}
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: i * 0.01 }}
          className={`h-7 flex items-center justify-center text-xs rounded-sm transition-all cursor-pointer ${
            isToday
              ? 'bg-neon-green/20 text-neon-green border border-neon-green/50'
              : 'text-gray-400 hover:text-white hover:bg-dark-600'
          }`}
        >
          {i}
        </motion.div>
      )
    }
    return days
  }

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      className="h-full"
    >
      <Card className="bg-dark-700/60 border-dark-600 w-full h-full">
        <CardContent className="p-4">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <i className="fa-solid fa-calendar text-neon-cyan"></i>
              <span className="text-xs text-gray-400">日历</span>
            </div>
            <div className="flex gap-1">
              <Button
                variant="ghost"
                size="icon-xs"
                onClick={prevMonth}
                className="text-gray-400 hover:text-white h-6 w-6"
              >
                <i className="fa-solid fa-chevron-left text-xs"></i>
              </Button>
              <Button
                variant="ghost"
                size="icon-xs"
                onClick={nextMonth}
                className="text-gray-400 hover:text-white h-6 w-6"
              >
                <i className="fa-solid fa-chevron-right text-xs"></i>
              </Button>
            </div>
          </div>

          <div className="text-sm font-semibold text-gray-200 mb-3 text-center">
            {year}年{month + 1}月
          </div>

          <div className="grid grid-cols-7 gap-1">
            {weekDays.map((day) => (
              <div key={day} className="h-5 flex items-center justify-center text-xs text-gray-500">
                {day}
              </div>
            ))}
            {renderDays()}
          </div>
        </CardContent>
      </Card>
    </motion.div>
  )
}
