// src/components/Timeline.svelte
<script>
  import entries from '../data/timeline.json'

  const DEFAULT_COUNT = 3
  let expanded = false

  $: visibleEntries = expanded ? entries : entries.slice(0, DEFAULT_COUNT)
  $: hasMore = entries.length > DEFAULT_COUNT

  function toggleExpand() {
    expanded = !expanded
  }
</script>

<section class="timeline">
  <div class="card">
    <div class="timeline-header">
      <span class="timeline-title">最近更新</span>
    </div>

    <div class="timeline-list">
      {#each visibleEntries as entry (entry.id)}
        <div class="timeline-item">
          <div class="timeline-dot"></div>
          <div class="timeline-line"></div>
          <div class="timeline-content">
            <span class="timeline-date">{entry.date}</span>
            <span class="timeline-entry-title">{entry.title}</span>
            {#if entry.desc}
              <span class="timeline-entry-desc">{entry.desc}</span>
            {/if}
          </div>
        </div>
      {/each}
    </div>

    {#if hasMore}
      <button class="expand-btn" on:click={toggleExpand}>
        {expanded ? '收起' : `展开全部 (${entries.length - DEFAULT_COUNT} 条更多)`}
        <i class="fa-solid fa-chevron-{expanded ? 'up' : 'down'}"></i>
      </button>
    {/if}
  </div>
</section>

<style>
  .timeline {
    width: 100%;
  }

  .card {
    background-color: #1a1a1a;
    border: 1px solid #2a2a2a;
    border-radius: 16px;
    padding: 20px 24px;
  }

  .timeline-header {
    margin-bottom: 14px;
    padding-bottom: 10px;
    border-bottom: 1px solid #2a2a2a;
  }

  .timeline-title {
    font-size: 13px;
    font-weight: 600;
    color: #ffffff;
  }

  .timeline-list {
    display: flex;
    flex-direction: column;
  }

  .timeline-item {
    position: relative;
    padding-left: 18px;
    padding-bottom: 14px;
  }

  .timeline-dot {
    position: absolute;
    left: 0;
    top: 4px;
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background-color: #ffffff;
    border: 2px solid #1a1a1a;
  }

  .timeline-line {
    position: absolute;
    left: 3px;
    top: 14px;
    width: 2px;
    bottom: 0;
    background-color: #2a2a2a;
  }

  .timeline-item:last-child .timeline-line {
    display: none;
  }

  .timeline-content {
    display: flex;
    flex-direction: column;
    gap: 3px;
  }

  .timeline-date {
    font-size: 11px;
    color: #666666;
  }

  .timeline-entry-title {
    font-size: 13px;
    color: #dddddd;
    font-weight: 500;
    line-height: 1.4;
  }

  .timeline-entry-desc {
    font-size: 12px;
    color: #888888;
    line-height: 1.4;
  }

  .expand-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
    width: 100%;
    padding: 10px;
    margin-top: 6px;
    background: none;
    border: none;
    border-top: 1px solid #2a2a2a;
    color: #888888;
    font-size: 12px;
    cursor: pointer;
    transition: all 0.2s ease-in-out;
    font-family: inherit;
  }

  .expand-btn:hover {
    color: #ffffff;
    background-color: #222222;
  }

  .expand-btn i {
    font-size: 10px;
    transition: transform 0.2s ease-in-out;
  }

  @media (max-width: 768px) {
    .card {
      padding: 16px 18px;
    }

    .timeline-entry-title {
      font-size: 12px;
    }

    .timeline-entry-desc {
      font-size: 11px;
    }
  }
</style>

// components/Timeline.tsx
'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { config } from '@/data/config'

const MAX_VISIBLE = 5

export default function Timeline() {
  const [expanded, setExpanded] = useState(false)
  const visibleItems = expanded ? config.timeline : config.timeline.slice(0, MAX_VISIBLE)

  return (
    <Card className="bg-dark-700/60 border-dark-600">
      <CardContent className="p-5">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold text-gray-200 flex items-center gap-2">
            <i className="fa-solid fa-timeline text-neon-cyan"></i>
            时间线
          </h3>
          {config.timeline.length > MAX_VISIBLE && (
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setExpanded(!expanded)}
              className="text-xs text-gray-400 hover:text-neon-cyan h-7"
            >
              <i className={`fa-solid ${expanded ? 'fa-chevron-up' : 'fa-chevron-down'}`}></i>
              {expanded ? '收起' : '查看全部'}
            </Button>
          )}
        </div>

        <div className="space-y-4">
          <AnimatePresence mode="popLayout">
            {visibleItems.map((item, index) => (
              <motion.div
                key={item.id}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ delay: index * 0.1 }}
                className="relative pl-6 border-l-2 border-dark-500 hover:border-neon-cyan/50 transition-colors"
              >
                <div className="absolute left-[-6px] top-1 w-3 h-3 rounded-full bg-neon-cyan/60" />
                <div className="text-xs text-gray-500 mb-1">{item.date}</div>
                <div className="text-sm text-gray-200 font-medium">{item.title}</div>
                <div className="text-xs text-gray-400 mt-1">{item.desc}</div>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      </CardContent>
    </Card>
  )
}
