// components/SocialButtons.tsx
'use client'

import { motion } from 'framer-motion'
import { Button } from '@/components/ui/button'

interface LinkItem {
  name: string
  url: string
  icon: string
}

interface SocialButtonsProps {
  onNavigate: (link: LinkItem) => void
}

const socialLinks: LinkItem[] = [
  { name: 'B站', url: 'https://space.bilibili.com/497846789', icon: 'fa-brands fa-bilibili' },
  { name: 'QQ', url: 'https://im.qq.com', icon: 'fa-brands fa-qq' },
  { name: 'Github', url: 'https://github.com/Flygeon', icon: 'fa-brands fa-github' },
]

export default function SocialButtons({ onNavigate }: SocialButtonsProps) {
  return (
    <div className="flex justify-center gap-4">
      {socialLinks.map((link, index) => (
        <motion.div
          key={link.name}
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.1 + index * 0.1 }}
        >
          <Button
            variant="outline"
            size="icon-lg"
            onClick={() => onNavigate(link)}
            className="w-14 h-14 bg-dark-800/80 border-dark-400/50 text-gray-400 hover:text-white hover:border-neon-green/50 hover:bg-dark-700/80 transition-all"
          >
            <i className={`${link.icon} text-lg`} />
          </Button>
          <span className="absolute -bottom-6 left-1/2 -translate-x-1/2 text-xs text-gray-500 opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">
            {link.name}
          </span>
        </motion.div>
      ))}
    </div>
  )
}

// src/components/SocialButtons.svelte
<script>
  // 社交链接配置
  const socialLinks = [
    {
      name: 'B站',
      icon: 'fa-brands fa-bilibili',
      url: 'https://space.bilibili.com/497846789'
    },
    {
      name: 'QQ',
      icon: 'fa-brands fa-qq',
      url: 'https://wpa.qq.com/msgrd?v=3&uin=123456789'
    },
    {
      name: 'Github',
      icon: 'fa-brands fa-github',
      url: 'https://github.com/flygeon'
    }
  ]
</script>

<section class="social-section">
  <div class="card">
    <div class="buttons-container">
      {#each socialLinks as link}
        <a 
          href={link.url} 
          target="_blank" 
          rel="noopener noreferrer"
          class="social-button"
        >
          <i class={link.icon}></i>
          <span>{link.name}</span>
        </a>
      {/each}
    </div>
  </div>
</section>

<style>
  .social-section {
    width: 100%;
  }

  .card {
    background-color: #1a1a1a;
    border: 1px solid #2a2a2a;
    border-radius: 16px;
    padding: 20px;
  }

  .buttons-container {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
    justify-content: center;
  }

  .social-button {
    display: flex;
    align-items: center;
    gap: 7px;
    height: 38px;
    padding: 0 16px;
    background-color: #111111;
    border: 1px solid #333333;
    border-radius: 999px;
    color: #dddddd;
    text-decoration: none;
    font-size: 13px;
    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
    cursor: pointer;
    white-space: nowrap;
    transform: scale(1);
    box-shadow: 0 0 0 rgba(255, 255, 255, 0);
  }

  .social-button:hover {
    background-color: #222222;
    border-color: #666666;
    color: #ffffff;
    transform: scale(1.06);
    box-shadow: 0 4px 16px rgba(255, 255, 255, 0.06);
  }

  .social-button:active {
    transform: scale(0.97);
    box-shadow: 0 1px 4px rgba(255, 255, 255, 0.03);
  }

  .social-button i {
    font-size: 14px;
    opacity: 0.85;
    transition: opacity 0.25s ease-in-out;
  }

  .social-button:hover i {
    opacity: 1;
  }

  @media (hover: none) and (pointer: coarse) {
    .social-button:active {
      background-color: #2a2a2a;
      border-color: #777777;
      color: #ffffff;
      transform: scale(0.96);
    }
  }

  @media (max-width: 768px) {
    .card {
      padding: 14px;
    }

    .buttons-container {
      gap: 8px;
    }

    .social-button {
      height: 34px;
      padding: 0 13px;
      font-size: 12px;
    }
  }
</style>
